SEED: 0
EXPERIMENT: 'default_experiment'
TRAIN:
    batch_size: 128
    # epochs: 32
    epochs: 50
    num_workers: 0
    # input_track_size: 16
    # output_track_size: 14
    # input_track_size: 50
    # output_track_size: 25
    # input_track_size: 30
    # output_track_size: 15
    # input_track_size: 90
    # output_track_size: 45
    input_track_size: 20
    output_track_size: 10
    # input_track_size: 60
    # output_track_size: 30
    lr: 0.0001
    lr_decay: 1
    lr_drop: true
    aux_weight: 0.2
    val_frequency: 1
    optimizer: "adam"
    max_grad_norm: 1.0
DATA:
    # joints: "somof"
    joints: ""
    deltas: False # Whether to predict pose deltas instead of the pose itself
    add_flips: True # Whether to add flipped sequences to dataset
    segmented: False # Whether to segment data into 30-frame sequences. If false, take every possibly 30-frame sequence (so 30x more data)
    aug_rotate: true # Whether to randomly rotate sequences about y (vertical) axis
    aug_scale: false # Whether to randomly scale squences
    aug_permute: True
    # aug_noise: True
    aug_noise: False
    train_datasets:
        - skelda
MODEL:
    # num_kps: 13 # Somof has 13 keypoints
    num_kps: 15
    num_layers: 6
    num_heads: 8
    dim_hidden: 256
    dim_feedforward: 1024
    type: "somoformer"
    eval_single: false
    dct_n: 30
    # dct_n: 10
    location_method: "grid"
    grid_len: 3
    grid_emb_size: 8
    checkpoint: ""
    output_scale: 1 # scale applied to model outputs. Since we predict deltas, it may help with training
    normalize_inputs: false # Whether to apply normalization to input sequences
    residual_connection: true
    learned_embedding: true
